

unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s # from C-b
set -g mouse on

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB"

set -g set-clipboard on # Makes vim clipboard yanking work
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in" # Makes tmux copy-mode work
bind-key -T copy-mode-vi C-q send -X rectangle-toggle
bind-key -T copy-mode-vi v send -X begin-selection
bind-key r source-file ~/.tmux.conf \; display "Reloaded from ~/.tmux.conf"


set -s escape-time 0
