# [terminal.shell] # Windows Specific Lines
# program = "C:\\Windows\\System32\\wsl.exe"

[window]
padding = { x = 10, y = 10 }
opacity = 1.00 

[font]
# normal = { family = "FiraMono Nerd Font", style = "Regular" }
# normal = { family = "Mononoki Nerd Font", style = "Regular" }
normal = { family = "JetBrainsMono NF", style = "Regular" }
# normal = { family = "IosevkaTerm NFM", style = "Regular" }
# normal = { family = "Monaspace Neon NF", style = "Regular" }
size = 9

[env]
TERM = "alacritty" # exports default name for apps like tmux and nvim to work

[keyboard]
# Makes it so C-BS deletes word in nvim
bindings = [{ key = "Back", mods = "Control", chars = "\x17" },] # /x17 == C-w


[colors.primary]
background = "#040214" # a very dark (black) blue

[colors.normal] # copied from solarize gnome
green   = "#398201"
blue = "#268BD2"
red = "#DC322F"
