# [terminal.shell] # Windows Specific Lines
# program = "C:\\Windows\\System32\\wsl.exe"

[window]
padding = { x = 10, y = 10 }
opacity = 1.00 # Slight transparency for modern feel

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
size = 12.0

[env]
TERM = "alacritty"

[keyboard]
# Makes it so C-BS deletes word in nvim
bindings = [{ key = "Back", mods = "Control", chars = "\x17" },]


[colors.primary]
background = "#040214"

[colors.normal] # copied from solarize gnome
green   = "#398201"
blue = "#268BD2"
red = "#DC322F"
